name: example
description: Example for ConditionalParentWidget

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  conditional_parent_widget:
    path: ../