name: conditional_parent_widget
description: Conditionally wrap a child widget with a parent widget.
version: 0.0.1
homepage: https://github.com/ltOgt/ConditionalParentWidget

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
