name: conditional_parent_widget
description: A new Flutter package project.
version: 0.0.1
author: ltogt
homepage: https://github.com/ltOgt

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter: null
dev_dependencies:
  flutter_test_ui: ^1.0.0
